package com.xworkz.userapp.constant;

public enum LocationEnum {
    BANGALORE, MUMBAI, DELHI, CHENNAI, HYDERABAD, PUNE,
    KOLKATA, AHMEDABAD, JAIPUR, CHANDIGARH, LUCKNOW,
    COIMBATORE, KOCHI, VISAKHAPATNAM, BHOPAL, INDORE,
    NAGPUR, SURAT, PATNA, GUWAHATI
}
